In [1]:
!gdown 1boIax8d9Sat6OJzkiIjjpqmtSZKuRYrx

Downloading...
From: https://drive.google.com/uc?id=1boIax8d9Sat6OJzkiIjjpqmtSZKuRYrx
To: C:\Users\cecea\ElectricCarData.csv

  0%|          | 0.00/8.20k [00:00<?, ?B/s]
100%|##########| 8.20k/8.20k [00:00<00:00, 8.21kB/s]
100%|##########| 8.20k/8.20k [00:00<00:00, 8.21kB/s]

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('ElectricCarData.csv')

In [5]:
data.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997

In [6]:
data.isnull().sum()

Brand              0
Model              0
AccelSec           0
TopSpeed_KmH       0
Range_Km           0
Efficiency_WhKm    0
FastCharge_KmH     0
RapidCharge        0
PowerTrain         0
PlugType           0
BodyStyle          0
Segment            0
Seats              0
PriceEuro          0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
colums_encode=['Brand','Model','PowerTrain','PlugType','BodyStyle','Segment','RapidCharge']
for col in colums_encode:
    encode=LabelEncoder()
    data[col]=encode.fit_transform(data[col])


data.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,30,46,4.6,233,450,161,940,1,0,2,7,3,5,55480
1,31,33,10.0,160,270,167,250,1,2,2,1,2,5,30000
2,23,0,4.7,210,400,181,620,1,0,2,2,3,5,56440
3,2,101,6.8,180,360,206,560,1,2,2,6,3,5,68040
4,9,78,9.5,145,170,168,190,1,2,2,1,1,4,32997

In [10]:
X=data.drop('PriceEuro',axis=1)
Y=data['PriceEuro']

In [12]:
X.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats
0,30,46,4.6,233,450,161,940,1,0,2,7,3,5
1,31,33,10.0,160,270,167,250,1,2,2,1,2,5
2,23,0,4.7,210,400,181,620,1,0,2,2,3,5
3,2,101,6.8,180,360,206,560,1,2,2,6,3,5
4,9,78,9.5,145,170,168,190,1,2,2,1,1,4

In [13]:
Y.head()

0    55480
1    30000
2    56440
3    68040
4    32997
Name: PriceEuro, dtype: int64

In [22]:
# Филтрирај редиците кои имаат '-' во колоната 'FastCharge_KmH'
data = data[data['FastCharge_KmH'] != '-']

# Проверка на резултатот
data.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,30,46,4.6,233,450,161,940,1,0,2,7,3,5,55480
1,31,33,10.0,160,270,167,250,1,2,2,1,2,5,30000
2,23,0,4.7,210,400,181,620,1,0,2,2,3,5,56440
3,2,101,6.8,180,360,206,560,1,2,2,6,3,5,68040
4,9,78,9.5,145,170,168,190,1,2,2,1,1,4,32997

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            98 non-null     int64
 1   Model            98 non-null     int64
 2   AccelSec         98 non-null     float64
 3   TopSpeed_KmH     98 non-null     int64
 4   Range_Km         98 non-null     int64
 5   Efficiency_WhKm  98 non-null     int64
 6   FastCharge_KmH   98 non-null     object
 7   RapidCharge      98 non-null     int64
 8   PowerTrain       98 non-null     int64
 9   PlugType         98 non-null     int64
 10  BodyStyle        98 non-null     int64
 11  Segment          98 non-null     int64
 12  Seats            98 non-null     int64
 13  PriceEuro        98 non-null     int64
dtypes: float64(1), int64(12), object(1)
memory usage: 11.5+ KB

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            103 non-null    int64
 1   Model            103 non-null    int64
 2   AccelSec         103 non-null    float64
 3   TopSpeed_KmH     103 non-null    int64
 4   Range_Km         103 non-null    int64
 5   Efficiency_WhKm  103 non-null    int64
 6   FastCharge_KmH   103 non-null    object
 7   RapidCharge      103 non-null    int64
 8   PowerTrain       103 non-null    int64
 9   PlugType         103 non-null    int64
 10  BodyStyle        103 non-null    int64
 11  Segment          103 non-null    int64
 12  Seats            103 non-null    int64
 13  PriceEuro        103 non-null    int64
dtypes: float64(1), int64(12), object(1)
memory usage: 11.4+ KB

In [21]:
X.sample(10)

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats
68,25,36,22.4,130,160,194,-,0,1,1,5,6,5
72,24,67,3.5,250,385,217,770,1,0,2,8,5,4
37,4,97,6.5,160,425,181,570,1,2,2,1,2,4
85,7,3,9.0,150,250,168,330,1,1,2,1,1,4
40,30,49,3.8,250,515,184,560,1,0,1,2,5,5
47,24,65,4.0,250,365,195,730,1,0,2,7,5,4
83,8,59,6.6,180,360,194,380,1,2,2,6,3,5
51,30,63,2.1,410,970,206,920,1,0,2,0,7,4
5,15,4,2.8,250,610,180,620,1,0,2,7,5,5
46,21,5,7.3,150,335,173,210,1,1,2,3,1,5

In [38]:
# Отстрани редици кои имаат '-' во која било од колоните
X_train = X_train[X_train != '-'].dropna()
Y_train = Y_train[Y_train != '-'].dropna()

# Ако се уште има податоци, можеш да примениш StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

# Применете го истиот процес на X_test ако е потребно
X_test = X_test[X_test != '-'].dropna()
X_test = scaler.transform(X_test)

AttributeError: 'numpy.ndarray' object has no attribute 'dropna'

In [32]:
Y_test.shape

(21,)

In [33]:
X_test.shape

(21, 13)

In [35]:
X_train.shape

(77, 13)

In [37]:
Y_train.shape

(82,)

In [31]:
from sklearn.tree import DecisionTreeRegressor

# Инициализирање на моделот DecisionTreeRegressor со зададени параметри
model = DecisionTreeRegressor(max_depth=5, min_samples_split=5, max_features=3)

# Обука на моделот со функцијата fit
model.fit(X_train, Y_train)

# Провери го моделот (можеш да го користиш за предвидување или оценување)
y_pred = model.predict(X_test)

# Ако сакаше да ја процениш точноста, можеш да го направиш тоа:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test, y_pred)
print(f"Mean Squared Error: {mse}")

ValueError: Number of labels=82 does not match number of samples=77

In [39]:
data.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,30,46,4.6,233,450,161,940,1,0,2,7,3,5,55480
1,31,33,10.0,160,270,167,250,1,2,2,1,2,5,30000
2,23,0,4.7,210,400,181,620,1,0,2,2,3,5,56440
3,2,101,6.8,180,360,206,560,1,2,2,6,3,5,68040
4,9,78,9.5,145,170,168,190,1,2,2,1,1,4,32997

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            98 non-null     int64
 1   Model            98 non-null     int64
 2   AccelSec         98 non-null     float64
 3   TopSpeed_KmH     98 non-null     int64
 4   Range_Km         98 non-null     int64
 5   Efficiency_WhKm  98 non-null     int64
 6   FastCharge_KmH   98 non-null     object
 7   RapidCharge      98 non-null     int64
 8   PowerTrain       98 non-null     int64
 9   PlugType         98 non-null     int64
 10  BodyStyle        98 non-null     int64
 11  Segment          98 non-null     int64
 12  Seats            98 non-null     int64
 13  PriceEuro        98 non-null     int64
dtypes: float64(1), int64(12), object(1)
memory usage: 11.5+ KB

In [49]:
data.sample(50)

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
19,19,12,7.3,150,185,156,260,1,1,2,1,1,4,31681
98,20,6,7.5,160,330,191,440,1,1,2,1,2,5,45000
88,27,27,6.2,180,400,193,540,1,0,2,6,2,5,47500
37,4,97,6.5,160,425,181,570,1,2,2,1,2,4,45000
72,24,67,3.5,250,385,217,770,1,0,2,8,5,4,150000
26,31,30,9.0,160,350,166,490,1,2,2,1,2,5,33000
13,2,100,4.0,200,450,178,650,1,2,2,7,3,5,65000
79,24,68,3.2,260,390,215,810,1,0,2,7,5,4,148301
35,20,40,7.3,157,325,172,390,1,1,3,1,2,5,37237
95,31,31,7.3,160,340,171,470,1,2,2,1,2,5,35575
100,20,8,5.9,200,325,194,440,1,0,2,1,2,5,50000
44,26,45,12.3,130,195,166,170,1,1,2,1,0,4,20129
39,18,20,5.0,200,350,171,440,1,0,2,6,2,5,45000
83,8,59,6.6,180,360,194,380,1,2,2,6,3,5,46900
102,3,42,7.5,190,400,238,480,1,0,2,6,4,5,62000
96,12,87,9.9,157,230,170,220,1,1,2,6,1,5,33133
87,1,95,6.8,190,295,219,470,1,0,2,6,4,5,69551
22,27,23,10.0,160,290,179,230,1,2,2,6,2,5,35000
58,5,82,9.7,150,250,180,380,1,1,2,6,2,5,40000
1,31,33,10.0,160,270,167,250,1,2,2,1,2,5,30000
90,1,93,4.5,210,320,270,510,1,0,2,6,4,5,93800
55,9,79,8.3,145,170,168,190,1,2,2,1,1,4,35921
61,30,54,3.7,241,410,177,900,1,0,2,6,3,7,65620
85,7,3,9.0,150,250,168,330,1,1,2,1,1,4,34900
50,1,91,5.7,200,365,237,590,1,0,2,6,4,5,79445
40,30,49,3.8,250,515,184,560,1,0,1,2,5,5,79990
97,3,41,7.5,190,325,222,420,1,2,2,6,4,5,53500
59,30,50,2.5,261,505,188,550,1,0,1,2,5,5,96990
14,10,35,9.7,165,250,153,210,1,1,2,2,2,5,34459
25,31,34,7.5,160,420,183,560,1,2,2,6,2,5,45000
41,10,37,9.9,155,255,154,210,1,1,2,6,1,5,33971
71,27,26,7.0,160,400,193,540,1,0,2,6,2,5,45000
20,21,13,8.1,150,275,164,420,1,1,2,1,1,5,29146
28,2,98,7.3,150,235,161,270,1,2,2,1,1,4,38017
12,10,38,7.9,167,400,160,380,1,1,2,6,1,5,40795
33,30,16,3.0,210,750,267,710,1,0,2,4,6,6,75000
80,31,29,7.3,160,340,171,470,1,2,2,1,2,5,38987
53,27,25,8.8,160,420,183,560,1,2,2,6,2,5,40000
74,29,64,9.0,140,225,156,270,1,1,2,1,2,5,25500
81,30,52,2.8,250,440,216,480,1,0,1,6,5,7,102990
73,3,43,5.5,190,390,244,460,1,0,2,6,4,5,64000
99,1,94,4.5,210,335,258,540,1,0,2,6,4,5,96050
5,15,4,2.8,250,610,180,620,1,0,2,7,5,5,105000
56,6,1,8.7,150,250,180,380,1,1,2,6,1,5,37422
18,16,74,8.2,140,220,193,260,1,1,2,6,1,5,30000
27,32,73,4.9,180,375,200,470,1,0,2,6,2,5,60437
92,12,88,7.9,167,365,175,320,1,1,2,6,1,5,36837
69,8,56,6.0,180,430,209,410,1,0,2,6,3,5,62900
43,27,11,12.3,130,195,166,170,1,1,2,1,0,4,24534
15,31,32,7.9,160,440,175,590,1,2,2,1,2,4,40936

In [50]:
X=data.drop('PriceEuro',axis=1)
Y=data['PriceEuro']

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [52]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
from sklearn.tree import DecisionTreeRegressor

# Инициализирање на моделот DecisionTreeRegressor со зададени параметри
model = DecisionTreeRegressor(max_depth=5, min_samples_split=5, max_features=0.5)

# Обука на моделот со функцијата fit
model.fit(X_train, Y_train)

# Провери го моделот (можеш да го користиш за предвидување или оценување)
y_pred = model.predict(X_test)

# Ако сакаше да ја процениш точноста, можеш да го направиш тоа:
from sklearn.metrics import mean_squared_error,  r2_score, mean_absolute_error
mse = mean_squared_error(Y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(mean_absolute_error(Y_test, y_pred), mean_squared_error(Y_test,y_pred), r2_score(Y_test,y_pred))

Mean Squared Error: 105710466.98309687
7222.853246753247 105710466.98309687 0.8486006932133686

In [60]:
from xgboost import XGBRegressor

# Инициализација на моделот со зададени параметри
model = XGBRegressor(
    n_estimators=100,         # Број на дрвја во ансамблот
    max_depth=5,              # Максимална длабочина на дрвјата
    learning_rate=0.1,        # Стапка на учење (learning rate)
    objective="reg:squarederror"  # Функција на целта за регресија
)

# Обука на моделот со функцијата fit
model.fit(X_train, Y_train)

# Пример за предвидување
y_pred = model.predict(X_test)
print(mean_absolute_error(Y_test, y_pred), mean_squared_error(Y_test,y_pred), r2_score(Y_test,y_pred))

5614.0642578125 52808744.48911057 0.9243669509887695